### ISSUE TITLE
Different build locations between versions

### ISSUE THREAD

**Issue by mjackson** [mastilver/module-to-cdn#3]
Sometimes packages will change where they put their UMD build in the npm package between versions. For example, in [version 16.0.0-alpha.6 of the `react` package](https://unpkg.com/react@16.0.0-alpha.6/) they kept their UMD builds in the `dist` directory. But in [version 16.0.0-alpha.7](https://unpkg.com/react@16.0.0-alpha.7/) they moved the build into a `umd` directory. Similarly, the `three` package moved their bundled files into the `build` directory between [version 0.77.0](https://unpkg.com/three@0.77.0/) and [version 0.77.1](https://unpkg.com/three@0.77.0/).

This means we need a way to dynamically resolve the unpkg URL based on the package version.

Perhaps we could do something like:

```js
import semver from 'semver'

const resolve = (packageName, version) => {
  if (packageName === 'react') {
    if (semver.gte(version, '16.0.0-alpha.7')) {
      // return paths that begin with /umd
    } else {
      // return the /dist paths
    }
  }
}
```

What do you think?

**Comment by mastilver** [comment]
I kind of knew about this limitation but didn't have a real example until now

What I'm planning to do:
- unit tests:
  - query all available versions of a specific module and test against it
  - have a daily build on travis, that way we will be notified when such issue happens with any modules
- update `modules.json` to follow:

```json
{
  "react": {
    "var": "React",
    "versions": {
      "<= 16.0.0-alpha.6": {
        "development": "...",
        "production": "..."
      },
      ">=16.0.0-alpha.7": {
        "development": "...",
        "production": "..."
      }
    }
  }
}
```

Does that make sense? I just want to reduce moving parts as much as possible and make editing as easy as possible

**Comment by mjackson** [comment]
Yes I think that's a great plan 👍
